// components/type-effect.vue
<script setup lang="ts">
import { useIntersectionObserver } from "@vueuse/core";
import { onUnmounted, ref } from "vue";

const props = defineProps<{
  text: string;
}>();

const container = ref(null);
const running = ref(false);
const value = ref("");
const cursor = ref<"unset" | "hidden">("unset");

const blink = () => {
  cursor.value = cursor.value === "hidden" ? "unset" : "hidden";
  setTimeout(blink, 800);
};

const type = () => {
  if (value.value !== props.text) {
    value.value = props.text.substring(0, value.value.length + 1);
    setTimeout(type, Math.random() * 150 + 50);
  } else {
    setTimeout(blink, 800);
  }
};

const { stop } = useIntersectionObserver(container, ([{ isIntersecting }]) => {
  if (isIntersecting && !running.value) {
    running.value = true;
    type();
  }
});
onUnmounted(stop);
</script>

<template>
  <div class="py-1" ref="container">
    <span>{{ value }}</span>
    <span class="p-1" :style="{ visibility: cursor }">█</span>
  </div>
</template>

// src/routes/type-effect.svelte
<script lang="ts">
	import { ss } from '$lib/style-string';

	const props = $props<{
		text: string;
	}>();

	let running = $state(false);
	let value = $state('');
	let cursor = $state<'unset' | 'hidden'>('unset');

	const blink = () => {
		cursor = cursor === 'hidden' ? 'unset' : 'hidden';
		setTimeout(blink, 800);
	};

	const type = () => {
		if (value !== props.text) {
			value = props.text.substring(0, value.length + 1);
			setTimeout(type, Math.random() * 150 + 50);
		} else {
			setTimeout(blink, 800);
		}
	};

	function setupObserver(node: HTMLDivElement) {
		const checkAndBegin = (e: any) => {
			if (e[0].isIntersecting && !running) {
				running = true;
				type();
				observer.disconnect();
			}
		};
		const observer = new IntersectionObserver(checkAndBegin, { threshold: 0.2 });
		observer.observe(node);
		return { destroy: () => observer.disconnect() };
	}
</script>

<div class="py-1" use:setupObserver>
	<span>{value}</span><span class="p-1" style={ss({ visibility: cursor })}>█</span>
</div>
